### ISSUE TITLE
Nice! But a nitpick on the manual...

### ISSUE THREAD

**Issue by Rmano** [alceu-frigeri/tikzquests#1]
Hi!

Very nice package, thank you!

One nitpick --- you should add a connection dot in the examples (see https://www.allaboutcircuits.com/textbook/reference/chpt-9/wires-and-connections/ , but basically, the convention is that plainly crossing wires do not make electrical contact; it was needed to avoid unreadable digital circuits...) 

![image](https://github.com/alceu-frigeri/tikzquests/assets/6414907/9aea0b9b-15db-4b68-8e01-45cc6c0e0aaa)

This, or you can use the "staggered" convention that removes all doubts (if you do not like connection dots)

![image](https://github.com/alceu-frigeri/tikzquests/assets/6414907/68b750b0-de8b-46d2-811d-0882c0f89a20)

**Comment by alceu-frigeri** [comment]
Hi Romano!
yeah, dot the connections or add jumps. 
I, personally use jumps (which is a pain when drawing with TikZ, dots are easier to add), and even jumps, I use them sparely (for instance, you got me on that circuit, the base is the input, so everything is connected to it, my bad ;) 

You are right, for the broad public, better to adhere to the dot convention.

**Comment by Rmano** [comment]
> Hi Romano! yeah, dot the connections or add jumps. I, personally use jumps (which is a pain when drawing with TikZ, dots are easier to add), and even jumps, I use them sparely (for instance, you got me on that circuit, the base is the input, so everything is connected to it, my bad ;)

Do not worry. I'm in teaching electronics in universities since 1994, so I have a kind of background routine for those things 😉

But yes, the dot convention is widely used now, and it's better to use it in my opinion.

**Comment by alceu-frigeri** [comment]
A new version, with corrected documentation is live by ctan ;)
